### ISSUE TITLE
graph set intersection AVX/AVX2的使用和性能数据

### ISSUE THREAD

**Issue by xuguruogu** [Caesar11/GraphSetIntersection#1]
我对您的工作很感兴趣，特别是intersection without BSR部分。如论文中提及，我认为该实现可以扩展到256bit指令集，比如：a队列取4 * 32bit，b队列取8 * 32bit进行intersection。

我看到代码中有对shuffling 256bit的支持。请问您是否考虑更新代码支持更新的指令集呢。

**Comment by Caesar11** [comment]
是的，字节检查过滤的思想可以拓展到256bit指令集，相应地可以增大数据并行度，实现起来不难。
我目前忙于毕业论文和其他的论文，暂时没时间写这边的代码，等过段时间可以考虑。
也欢迎您交流或贡献代码：）
